meta:
  url: https://ygkn.github.io/encouragement-of-web/
  title: ウェブノススメ
  description: Encouragement of Web.
  siteName: ウェブノススメ
  sns: ["twitter"]
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: []
    theme: default # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
